### ISSUE TITLE
Cannot use `treesit-langs` on Emacs 30 (last commit)

### ISSUE THREAD

**Issue by abougouffa** [kiennq/treesit-langs#1]
Hello,

Thank you for this package, 

I presume that this package is in an early stage, but I wonder if it is usable?

I'm trying to use it with Emacs 30, compiled with tree-sitter support, I can download the grammars (the version in the package `0.12.0` doesn't match the version in the repo `0.12.12`, I installed it manually).

However, I didn't get so much from it, for example, if I call the command `treesit-hl-enable` in, let's say `c-mode` or `c-ts-mode`, I get `treesit-hl-enable: No query patterns for c`. I get the same message in any other mode. Even if the queries are available and the binaries are installed correctly.

### Edit 1
A sub-problem was that the `(treesit-langs--hl-query-path lang)` was returning a file which doesn't exist. When I tracked this down, It turned out that the `queries` directory was available in the `straight/repos` directory but not the `straight/build` one, I fixed this by changing straight's recipe. Now the `treesit-hl-enable` seems to be happy (no more `No query patterns...` message. However, I didn't notice any difference in the syntax highlighting before and after calling it!

```elisp
(use-package treesit-langs
  ;; Using this recipe fixes the queries problem
  :straight (:host github :repo "kiennq/treesit-langs" :files (:defaults "*"))
  :config
  (treesit-langs-install-grammars :skip-if-installed "0.12.12"))
```

### Edit 2 (MAYBE SOLVED!)
I was using `treesit-hl-enable` on `X-mode`, but when I switched to the `X-ts-mode`, it worked. I guess I can close this issue. However, I would like to know if I'm guessing right: Is `treesit-hl-enable` only supports the new `X-ts-mode`s, or it can support the classic `X-mode`s?.

**Comment by kiennq** [comment]
Here is my config:
``` elisp
(use-package treesit-langs
  :quelpa (treesit-langs :repo "kiennq/treesit-langs"
                         :fetcher github
                         :files ("treesit-*.el" "queries"))
  :defer t
  :hook ((prog-mode text-mode) .
         (lambda ()
           (ignore-errors
             (treesit-hl-enable))))
  :custom
  (treesit-langs-grammar-dir (expand-file-name ".cache/tree-sitter/" user-emacs-directory))
  (treesit-langs-git-dir nil))
```

If you don't have any parser, this package should download the latest version from the Github release, else you can download the latest parsers (on-demand) by using `C-u M-x treesit-langs-install-grammars` without having to go to Github to check

**Comment by abougouffa** [comment]
Thank you for the answer, I'm using it side-by-side with the `tree-sitter-langs`, it works fine with `X-ts-mode`s.

Thanks again!

**Comment by kiennq** [comment]
@abougouffa I've fixed the issue of not highlighting in non `-ts-mode`. You can try it if you want now
