### ISSUE TITLE
Error on python file

### ISSUE THREAD

**Issue by dvzubarev** [kiennq/treesit-langs#2]
I was trying to enable highlighting using `treesit-hl-toggle` for python. It gave me an error: something about  wrong query.
I tracked it down to this rule `"\"" @string`  in `queries/python/highlights.scm`.
I can reproduce this error by running `(treesit-query-validate 'python "\"\\\"\"
@treesit-face-string")` in ielm.

After deleting this rule everything works fine.
I'm not sure why this rule is there. There is no such rule in vanilla [tree-sitter-python](https://github.com/tree-sitter/tree-sitter-python/blob/82f5c9937fe4300b4bec3ee0e788d642c77aab2c/queries/highlights.scm#L49) or in [python-ts-mode](https://github.com/emacs-mirror/emacs/blob/c71c949618dba7a371f94a8f0d1668e717c69fb2/lisp/progmodes/python.el#L1106)
Also `queries/python/highlights.scm` already contains `(string) @string` rule.

Emacs 29.1

**Comment by kiennq** [comment]
It's from the previous emacs module tree-sitter queries.
I updated this to use the `nvim-tree-sitter` rules at 21f3a8c
